export default {
    theme: {
        extend: {
            fontFamily: {
                ubuntu: ['UbuntuMono', 'monospace'],
                departure: ['DepartureMono', 'monospace'],
                system: ['system-ui', 'sans-serif'],
                humanist: [
                    'Optima',
                    'Candara',
                    '"Noto Sans"',
                    'source-sans-pro',
                    'sans-serif',
                ],
                industrial: [
                    'Bahnschrift',
                    '"DIN Alternate"',
                    '"Franklin Gothic Medium"',
                    '"Nimbus Sans Narrow"',
                    'sans-serif-condensed',
                    'sans-serif',
                ],
            },
            colors: {
                primary: {
                    DEFAULT: '#E7187E',
                    50: '#F8BEDB',
                    100: '#F6ACD1',
                    200: '#F287BC',
                    300: '#EE62A8',
                    400: '#EB3D93',
                    500: '#E7187E',
                    600: '#B41363',
                    700: '#810E47',
                    800: '#4E082B',
                    900: '#1C030F',
                    950: '#020001',
                },
                surface: {
                    DEFAULT: '#838C91',
                    50: '#E4E6E7',
                    100: '#D9DCDD',
                    200: '#C4C8CA',
                    300: '#AEB4B7',
                    400: '#98A0A4',
                    500: '#838C91',
                    600: '#677074',
                    700: '#4D5356',
                    800: '#323739',
                    900: '#181A1B',
                    950: '#0B0C0C',
                },
                ink: {
                    DEFAULT: '#8D868B',
                    50: '#FDFCFC',
                    100: '#F0EFF0',
                    200: '#D7D5D7',
                    300: '#BFBBBD',
                    400: '#A6A0A4',
                    500: '#8D868B',
                    600: '#716A6F',
                    700: '#544F52',
                    800: '#373436',
                    900: '#1A191A',
                    950: '#0C0B0C',
                },
            },
        },
    },
    plugins: [],
}